import { ChartDataPoint, KPIStats, Shipment, CategoryStat, ClienteMayorista, EcommerceTienda, Proveedor, InventarioItem, Operacion, UrgentItem, ProximoHito, PagoProximo, CajaBreakdown } from './types';

export const REVENUE_DATA: ChartDataPoint[] = [
  { month: 'Ene', maritimo: 45000, aereo: 12000 },
  { month: 'Feb', maritimo: 52000, aereo: 15000 },
  { month: 'Mar', maritimo: 48000, aereo: 18000 },
  { month: 'Abr', maritimo: 61000, aereo: 14000 },
  { month: 'May', maritimo: 55000, aereo: 16000 },
  { month: 'Jun', maritimo: 58000, aereo: 11000 },
  { month: 'Jul', maritimo: 72000, aereo: 19000 },
  { month: 'Ago', maritimo: 68000, aereo: 22000 },
  { month: 'Sep', maritimo: 64000, aereo: 17000 },
  { month: 'Oct', maritimo: 71000, aereo: 21000 },
  { month: 'Nov', maritimo: 78000, aereo: 24000 },
  { month: 'Dic', maritimo: 85000, aereo: 28000 },
];

export const KPIS: KPIStats[] = [
  {
    label: "Valor en Tránsito",
    value: "$247,320",
    growth: 12.4,
    chartData: [{ val: 40 }, { val: 60 }, { val: 55 }, { val: 80 }, { val: 95 }]
  },
  {
    label: "Embarques Activos",
    value: "8",
    growth: 2,
    chartData: [{ val: 20 }, { val: 40 }, { val: 30 }, { val: 50 }, { val: 70 }]
  },
  {
    label: "Por Nacionalizar",
    value: "3",
    growth: -1,
    chartData: [{ val: 45 }, { val: 35 }, { val: 50 }, { val: 40 }, { val: 30 }]
  },
  {
    label: "Facturado Mes",
    value: "$891,450",
    growth: 18.5,
    chartData: [{ val: 30 }, { val: 50 }, { val: 60 }, { val: 75 }, { val: 90 }]
  }
];

export const RECENT_SHIPMENTS: Shipment[] = [
  {
    id: "EMB-2025-089",
    productName: "Electrónica Consumo Masivo",
    productImage: "https://picsum.photos/40/40?random=1",
    date: "3 Ene 2025",
    status: "transito",
    value: 45000,
    origen: "Shanghai",
    tipo: "maritimo",
    eta: "15 Ene",
    progreso: 65
  },
  {
    id: "EMB-2025-091",
    productName: "Accesorios Mascotas Premium",
    productImage: "https://picsum.photos/40/40?random=2",
    date: "8 Ene 2025",
    status: "aduana",
    value: 28000,
    origen: "Shenzhen",
    tipo: "aereo",
    eta: "10 Ene",
    progreso: 90
  },
  {
    id: "EMB-2025-092",
    productName: "Smart Home Devices",
    productImage: "https://picsum.photos/40/40?random=3",
    date: "10 Ene 2025",
    status: "transito",
    value: 62000,
    origen: "Ningbo",
    tipo: "maritimo",
    eta: "28 Ene",
    progreso: 35
  },
  {
    id: "EMB-2025-093",
    productName: "Muñecas Colección 2025",
    productImage: "https://picsum.photos/40/40?random=4",
    date: "12 Ene 2025",
    status: "produccion",
    value: 38000,
    origen: "Yiwu",
    tipo: "maritimo",
    eta: "10 Feb",
    progreso: 15
  },
  {
    id: "EMB-2025-094",
    productName: "Repuestos Electrónicos",
    productImage: "https://picsum.photos/40/40?random=5",
    date: "15 Ene 2025",
    status: "demorado",
    value: 19500,
    origen: "Guangzhou",
    tipo: "aereo",
    eta: "20 Ene",
    progreso: 45
  }
];

export const CATEGORIES: CategoryStat[] = [
  { name: 'Electrónica', value: 420000, color: '#3b82f6' },
  { name: 'Mascotas', value: 185000, color: '#06b6d4' },
  { name: 'Smart Home', value: 156000, color: '#8b5cf6' },
  { name: 'Juguetes/Colección', value: 98000, color: '#f59e0b' },
  { name: 'Otros', value: 32450, color: '#22c55e' },
];

export const DONUT_DATA = [
  { name: 'Mayorista', value: 72, fill: '#3b82f6' },
  { name: 'Ecommerce', value: 28, fill: '#10b981' },
];

export const CLIENTES_MAYORISTAS: ClienteMayorista[] = [
  { id: 'CLI-001', nombre: 'Distribuidora del Sur SRL', categoria: 'A', deuda: 180000, comprasMes: 245000 },
  { id: 'CLI-002', nombre: 'TechStore Argentina', categoria: 'A', deuda: 350000, comprasMes: 412000 },
  { id: 'CLI-003', nombre: 'Electro Mendoza', categoria: 'B', deuda: 0, comprasMes: 89000 },
  { id: 'CLI-004', nombre: 'Importaciones Córdoba SA', categoria: 'A', deuda: 120000, comprasMes: 320000 },
  { id: 'CLI-005', nombre: 'Bazar Express', categoria: 'C', deuda: 65000, comprasMes: 45000 },
];

export const ECOMMERCE_STATS: EcommerceTienda[] = [
  { tienda: 'Pet Vogue', ventas: 156, ingresos: 2340000, crecimiento: 18.5 },
  { tienda: 'Royal Dolls', ventas: 89, ingresos: 1890000, crecimiento: 24.1 },
  { tienda: 'CoreSmart', ventas: 67, ingresos: 3120000, crecimiento: 31.2 },
];

export const PROVEEDORES: Proveedor[] = [
  {
    id: 'PROV-001',
    nombre: 'Shenzhen Electronics Co.',
    ciudad: 'Shenzhen',
    productos: ['Electrónica', 'Smart Home', 'Accesorios'],
    rating: 4.8,
    comprasTotal: 892000,
    ultimaCompra: '2025-01-05',
    estado: 'activo',
    contacto: 'sales@shenzhenelec.cn'
  },
  {
    id: 'PROV-002',
    nombre: 'Yiwu Pet Supplies Ltd.',
    ciudad: 'Yiwu',
    productos: ['Mascotas', 'Accesorios Pet'],
    rating: 4.5,
    comprasTotal: 456000,
    ultimaCompra: '2025-01-08',
    estado: 'activo',
    contacto: 'export@yiwupet.com'
  },
  {
    id: 'PROV-003',
    nombre: 'Guangzhou Toys Factory',
    ciudad: 'Guangzhou',
    productos: ['Juguetes', 'Muñecas', 'Colección'],
    rating: 4.2,
    comprasTotal: 324000,
    ultimaCompra: '2024-12-20',
    estado: 'activo',
    contacto: 'info@gztoys.cn'
  },
  {
    id: 'PROV-004',
    nombre: 'Ningbo Smart Tech',
    ciudad: 'Ningbo',
    productos: ['Smart Home', 'IoT', 'Domótica'],
    rating: 4.6,
    comprasTotal: 567000,
    ultimaCompra: '2025-01-10',
    estado: 'activo',
    contacto: 'trade@nbsmart.com'
  },
  {
    id: 'PROV-005',
    nombre: 'Shanghai Components Inc.',
    ciudad: 'Shanghai',
    productos: ['Repuestos', 'Componentes', 'Electrónica'],
    rating: 3.9,
    comprasTotal: 189000,
    ultimaCompra: '2024-11-15',
    estado: 'pendiente',
    contacto: 'parts@shcomp.cn'
  },
  {
    id: 'PROV-006',
    nombre: 'Dongguan Accessories',
    ciudad: 'Dongguan',
    productos: ['Accesorios Móvil', 'Cables', 'Cargadores'],
    rating: 4.1,
    comprasTotal: 234000,
    ultimaCompra: '2024-12-28',
    estado: 'activo',
    contacto: 'sales@dgacc.com'
  }
];

export const INVENTARIO: InventarioItem[] = [
  {
    id: 'INV-001',
    sku: 'ELEC-CASE-IP15',
    nombre: 'Fundas iPhone 15 Pro Max',
    categoria: 'Electrónica',
    stock: 12,
    stockMinimo: 50,
    costoUSD: 2.50,
    precioVenta: 8500,
    ubicacion: 'Depósito A - Estante 3',
    ultimoMovimiento: '2025-01-06'
  },
  {
    id: 'INV-002',
    sku: 'ELEC-CHRG-USBC',
    nombre: 'Cargadores USB-C 20W',
    categoria: 'Electrónica',
    stock: 0,
    stockMinimo: 100,
    costoUSD: 3.20,
    precioVenta: 12000,
    ubicacion: 'Depósito A - Estante 5',
    ultimoMovimiento: '2025-01-02'
  },
  {
    id: 'INV-003',
    sku: 'PET-COLLAR-LED',
    nombre: 'Collares LED Mascotas',
    categoria: 'Mascotas',
    stock: 234,
    stockMinimo: 100,
    costoUSD: 1.80,
    precioVenta: 6500,
    ubicacion: 'Depósito B - Estante 1',
    ultimoMovimiento: '2025-01-07'
  },
  {
    id: 'INV-004',
    sku: 'SMART-BULB-RGB',
    nombre: 'Bombillas Smart WiFi RGB',
    categoria: 'Smart Home',
    stock: 89,
    stockMinimo: 80,
    costoUSD: 4.50,
    precioVenta: 15000,
    ubicacion: 'Depósito A - Estante 8',
    ultimoMovimiento: '2025-01-05'
  },
  {
    id: 'INV-005',
    sku: 'TOY-DOLL-COL25',
    nombre: 'Muñecas Colección 2025',
    categoria: 'Juguetes',
    stock: 45,
    stockMinimo: 30,
    costoUSD: 8.90,
    precioVenta: 28000,
    ubicacion: 'Depósito C - Estante 2',
    ultimoMovimiento: '2025-01-04'
  },
  {
    id: 'INV-006',
    sku: 'ELEC-AIRPOD-CLN',
    nombre: 'AirPods Clone Pro',
    categoria: 'Electrónica',
    stock: 8,
    stockMinimo: 30,
    costoUSD: 12.00,
    precioVenta: 35000,
    ubicacion: 'Depósito A - Estante 1',
    ultimoMovimiento: '2025-01-03'
  },
  {
    id: 'INV-007',
    sku: 'PET-BED-LUXE',
    nombre: 'Camas Premium Mascotas',
    categoria: 'Mascotas',
    stock: 156,
    stockMinimo: 50,
    costoUSD: 15.00,
    precioVenta: 45000,
    ubicacion: 'Depósito B - Estante 4',
    ultimoMovimiento: '2025-01-06'
  },
  {
    id: 'INV-008',
    sku: 'SMART-PLUG-WIFI',
    nombre: 'Enchufes Inteligentes WiFi',
    categoria: 'Smart Home',
    stock: 312,
    stockMinimo: 150,
    costoUSD: 3.80,
    precioVenta: 11000,
    ubicacion: 'Depósito A - Estante 9',
    ultimoMovimiento: '2025-01-07'
  }
];

// ============ OPERACIONES (FASE 2A + 2D) ============

export const OPERACIONES: Operacion[] = [
  {
    id: 'OP-097',
    nombre: 'Juguetes Verano 2025',
    descripcion: 'Muñecas y juguetes colección verano',
    etapa: 'produccion',
    riesgo: 'bajo',
    proveedor: 'Guangzhou Toys Factory',
    proveedorCiudad: 'Guangzhou',
    forwarder: 'DHL Global Forwarding',
    despachante: 'García & Asociados',
    incoterm: 'FOB Guangzhou',
    ncm: '9503.00.99',
    tipoContenedor: '1x40\' HQ',
    tipoTransporte: 'maritimo',
    fechaPO: '2024-12-15',
    fechaETD: '2025-01-25',
    fechaETA: '2025-02-20',
    fechaArribo: null,
    freeTimeDias: null,
    freeTimeVence: null,
    canalAduana: null,
    observacionesAduana: null,
    montoTotalUSD: 45000,
    costos: [
      { concepto: 'Mercadería', estimadoUSD: 38000, realUSD: 38000 },
      { concepto: 'Flete', estimadoUSD: 4200, realUSD: null },
      { concepto: 'Seguro', estimadoUSD: 500, realUSD: 480 },
      { concepto: 'Gastos destino', estimadoUSD: 2300, realUSD: null },
    ],
    pagos: [
      { id: 'PAG-097-1', concepto: 'anticipo_proveedor', descripcion: 'Anticipo 30%', montoUSD: 11400, fechaVencimiento: '2024-12-20', estado: 'pagado' },
      { id: 'PAG-097-2', concepto: 'saldo_proveedor', descripcion: 'Saldo 70%', montoUSD: 26600, fechaVencimiento: '2025-01-20', estado: 'pendiente' },
    ],
    documentos: [
      { tipo: 'invoice', nombre: 'Invoice', estado: 'validado', fechaRecibido: '2024-12-18', obligatorio: true },
      { tipo: 'packing_list', nombre: 'Packing List', estado: 'pendiente', obligatorio: true },
      { tipo: 'bl', nombre: 'B/L', estado: 'pendiente', obligatorio: true },
    ],
    hitos: [
      { tipo: 'po', descripcion: 'PO emitida', fecha: '2024-12-15', completado: true },
      { tipo: 'produccion_fin', descripcion: 'Fin producción', fecha: '2025-01-20', completado: false },
      { tipo: 'etd', descripcion: 'ETD Guangzhou', fecha: '2025-01-25', completado: false },
      { tipo: 'eta', descripcion: 'ETA Buenos Aires', fecha: '2025-02-20', completado: false },
    ],
    responsable: 'Operaciones',
    alertas: [],
    bloqueo: null,
    proximaAccion: { texto: 'Confirmar fin producción', owner: 'Operaciones' }
  },
  {
    id: 'OP-098',
    nombre: 'Accesorios Mascotas Q1',
    descripcion: 'Collares, correas y accesorios premium',
    etapa: 'produccion',
    riesgo: 'bajo',
    proveedor: 'Yiwu Pet Supplies Ltd.',
    proveedorCiudad: 'Yiwu',
    forwarder: 'Kuehne+Nagel',
    despachante: 'García & Asociados',
    incoterm: 'FOB Ningbo',
    ncm: '4201.00.00',
    tipoContenedor: '1x20\' FCL',
    tipoTransporte: 'maritimo',
    fechaPO: '2024-12-20',
    fechaETD: '2025-01-30',
    fechaETA: '2025-02-25',
    fechaArribo: null,
    freeTimeDias: null,
    freeTimeVence: null,
    canalAduana: null,
    observacionesAduana: null,
    montoTotalUSD: 23000,
    costos: [
      { concepto: 'Mercadería', estimadoUSD: 18500, realUSD: 18500 },
      { concepto: 'Flete', estimadoUSD: 2800, realUSD: null },
      { concepto: 'Seguro', estimadoUSD: 300, realUSD: null },
      { concepto: 'Gastos destino', estimadoUSD: 1400, realUSD: null },
    ],
    pagos: [
      { id: 'PAG-098-1', concepto: 'anticipo_proveedor', descripcion: 'Anticipo 30%', montoUSD: 5550, fechaVencimiento: '2024-12-25', estado: 'pagado' },
      { id: 'PAG-098-2', concepto: 'saldo_proveedor', descripcion: 'Saldo 70%', montoUSD: 12950, fechaVencimiento: '2025-01-25', estado: 'pendiente' },
    ],
    documentos: [
      { tipo: 'invoice', nombre: 'Invoice', estado: 'validado', fechaRecibido: '2024-12-22', obligatorio: true },
      { tipo: 'packing_list', nombre: 'Packing List', estado: 'pendiente', obligatorio: true },
      { tipo: 'bl', nombre: 'B/L', estado: 'pendiente', obligatorio: true },
    ],
    hitos: [
      { tipo: 'po', descripcion: 'PO emitida', fecha: '2024-12-20', completado: true },
      { tipo: 'produccion_fin', descripcion: 'Fin producción', fecha: '2025-01-25', completado: false },
    ],
    responsable: 'Operaciones',
    alertas: [],
    bloqueo: null,
    proximaAccion: { texto: 'Seguimiento producción', owner: 'Operaciones' }
  },
  {
    id: 'OP-094',
    nombre: 'Smart Home Lote 3',
    descripcion: 'Bombillas, enchufes y sensores WiFi',
    etapa: 'en_transito',
    riesgo: 'medio',
    proveedor: 'Ningbo Smart Tech',
    proveedorCiudad: 'Ningbo',
    forwarder: 'MSC',
    despachante: 'Bianchi Despachantes',
    incoterm: 'FOB Ningbo',
    ncm: '8539.50.00',
    tipoContenedor: '1x20\' FCL',
    tipoTransporte: 'maritimo',
    fechaPO: '2024-11-20',
    fechaETD: '2024-12-28',
    fechaETA: '2025-01-19',
    fechaArribo: null,
    freeTimeDias: 14,
    freeTimeVence: null,
    canalAduana: null,
    observacionesAduana: null,
    montoTotalUSD: 32000,
    costos: [
      { concepto: 'Mercadería', estimadoUSD: 26000, realUSD: 26000 },
      { concepto: 'Flete', estimadoUSD: 3200, realUSD: 3200 },
      { concepto: 'Seguro', estimadoUSD: 400, realUSD: 400 },
      { concepto: 'Gastos destino', estimadoUSD: 2400, realUSD: null },
    ],
    pagos: [
      { id: 'PAG-094-1', concepto: 'anticipo_proveedor', descripcion: 'Anticipo 30%', montoUSD: 7800, fechaVencimiento: '2024-11-25', estado: 'pagado' },
      { id: 'PAG-094-2', concepto: 'saldo_proveedor', descripcion: 'Saldo 70%', montoUSD: 18200, fechaVencimiento: '2024-12-25', estado: 'pagado' },
      { id: 'PAG-094-3', concepto: 'flete', descripcion: 'Flete MSC', montoUSD: 3200, fechaVencimiento: '2024-12-28', estado: 'pagado' },
    ],
    documentos: [
      { tipo: 'invoice', nombre: 'Invoice', estado: 'validado', fechaRecibido: '2024-11-28', obligatorio: true },
      { tipo: 'packing_list', nombre: 'Packing List', estado: 'validado', fechaRecibido: '2024-12-20', obligatorio: true },
      { tipo: 'bl', nombre: 'B/L', estado: 'pendiente', obligatorio: true },
      { tipo: 'seguro', nombre: 'Certificado Seguro', estado: 'validado', fechaRecibido: '2024-12-26', obligatorio: true },
    ],
    hitos: [
      { tipo: 'po', descripcion: 'PO emitida', fecha: '2024-11-20', completado: true },
      { tipo: 'produccion_fin', descripcion: 'Fin producción', fecha: '2024-12-20', completado: true },
      { tipo: 'etd', descripcion: 'ETD Ningbo', fecha: '2024-12-28', completado: true },
      { tipo: 'eta', descripcion: 'ETA Buenos Aires', fecha: '2025-01-19', completado: false },
      { tipo: 'cutoff', descripcion: 'Cut-off documentos', fecha: '2025-01-10', completado: false },
    ],
    responsable: 'Logística',
    alertas: ['B/L pendiente - ETA en 12 días'],
    bloqueo: null,
    proximaAccion: { texto: 'Solicitar B/L a forwarder', owner: 'Logística' }
  },
  {
    id: 'OP-091',
    nombre: 'Repuestos Electrónicos',
    descripcion: 'Pantallas, baterías y flex para reparación',
    etapa: 'en_transito',
    riesgo: 'bajo',
    proveedor: 'Shanghai Components Inc.',
    proveedorCiudad: 'Shanghai',
    forwarder: 'Maersk',
    despachante: 'García & Asociados',
    incoterm: 'CIF Buenos Aires',
    ncm: '8529.90.00',
    tipoContenedor: 'LCL 8 CBM',
    tipoTransporte: 'maritimo',
    fechaPO: '2024-11-15',
    fechaETD: '2024-12-20',
    fechaETA: '2025-01-28',
    fechaArribo: null,
    freeTimeDias: 14,
    freeTimeVence: null,
    canalAduana: null,
    observacionesAduana: null,
    montoTotalUSD: 41000,
    costos: [
      { concepto: 'Mercadería', estimadoUSD: 35000, realUSD: 35000 },
      { concepto: 'Flete', estimadoUSD: 3500, realUSD: 3500 },
      { concepto: 'Seguro', estimadoUSD: 500, realUSD: 500 },
      { concepto: 'Gastos destino', estimadoUSD: 2000, realUSD: null },
    ],
    pagos: [
      { id: 'PAG-091-1', concepto: 'anticipo_proveedor', descripcion: 'Anticipo 50%', montoUSD: 17500, fechaVencimiento: '2024-11-20', estado: 'pagado' },
      { id: 'PAG-091-2', concepto: 'saldo_proveedor', descripcion: 'Saldo 50%', montoUSD: 17500, fechaVencimiento: '2025-01-15', estado: 'pendiente' },
    ],
    documentos: [
      { tipo: 'invoice', nombre: 'Invoice', estado: 'validado', fechaRecibido: '2024-11-18', obligatorio: true },
      { tipo: 'packing_list', nombre: 'Packing List', estado: 'validado', fechaRecibido: '2024-12-15', obligatorio: true },
      { tipo: 'bl', nombre: 'B/L', estado: 'validado', fechaRecibido: '2024-12-22', obligatorio: true },
      { tipo: 'cert_origen', nombre: 'Certificado Origen', estado: 'pendiente', obligatorio: true },
    ],
    hitos: [
      { tipo: 'po', descripcion: 'PO emitida', fecha: '2024-11-15', completado: true },
      { tipo: 'etd', descripcion: 'ETD Shanghai', fecha: '2024-12-20', completado: true },
      { tipo: 'eta', descripcion: 'ETA Buenos Aires', fecha: '2025-01-28', completado: false },
    ],
    responsable: 'Logística',
    alertas: ['Certificado de origen pendiente'],
    bloqueo: null,
    proximaAccion: { texto: 'Gestionar cert. origen', owner: 'Logística' }
  },
  {
    id: 'OP-092',
    nombre: 'Accesorios Móvil Q1',
    descripcion: 'Cables, cargadores y fundas',
    etapa: 'en_transito',
    riesgo: 'bajo',
    proveedor: 'Dongguan Accessories',
    proveedorCiudad: 'Dongguan',
    forwarder: 'Evergreen',
    despachante: 'Bianchi Despachantes',
    incoterm: 'FOB Shenzhen',
    ncm: '8544.42.00',
    tipoContenedor: '1x20\' FCL',
    tipoTransporte: 'maritimo',
    fechaPO: '2024-11-25',
    fechaETD: '2024-12-30',
    fechaETA: '2025-01-25',
    fechaArribo: null,
    freeTimeDias: 14,
    freeTimeVence: null,
    canalAduana: null,
    observacionesAduana: null,
    montoTotalUSD: 19000,
    costos: [
      { concepto: 'Mercadería', estimadoUSD: 15000, realUSD: 15000 },
      { concepto: 'Flete', estimadoUSD: 2500, realUSD: 2500 },
      { concepto: 'Seguro', estimadoUSD: 300, realUSD: 300 },
      { concepto: 'Gastos destino', estimadoUSD: 1200, realUSD: null },
    ],
    pagos: [
      { id: 'PAG-092-1', concepto: 'anticipo_proveedor', descripcion: 'Anticipo 30%', montoUSD: 4500, fechaVencimiento: '2024-11-30', estado: 'pagado' },
      { id: 'PAG-092-2', concepto: 'saldo_proveedor', descripcion: 'Saldo 70%', montoUSD: 10500, fechaVencimiento: '2024-12-28', estado: 'pagado' },
    ],
    documentos: [
      { tipo: 'invoice', nombre: 'Invoice', estado: 'validado', fechaRecibido: '2024-11-28', obligatorio: true },
      { tipo: 'packing_list', nombre: 'Packing List', estado: 'validado', fechaRecibido: '2024-12-25', obligatorio: true },
      { tipo: 'bl', nombre: 'B/L', estado: 'validado', fechaRecibido: '2025-01-02', obligatorio: true },
    ],
    hitos: [
      { tipo: 'po', descripcion: 'PO emitida', fecha: '2024-11-25', completado: true },
      { tipo: 'etd', descripcion: 'ETD Shenzhen', fecha: '2024-12-30', completado: true },
      { tipo: 'eta', descripcion: 'ETA Buenos Aires', fecha: '2025-01-25', completado: false },
    ],
    responsable: 'Logística',
    alertas: [],
    bloqueo: null,
    proximaAccion: { texto: 'Monitorear tracking', owner: 'Logística' }
  },
  {
    id: 'OP-089',
    nombre: 'Electrónica Consumo',
    descripcion: 'Auriculares, parlantes y accesorios tech',
    etapa: 'arribo',
    riesgo: 'medio',
    proveedor: 'Shenzhen Electronics Co.',
    proveedorCiudad: 'Shenzhen',
    forwarder: 'DHL Global Forwarding',
    despachante: 'García & Asociados',
    incoterm: 'FOB Shenzhen',
    ncm: '8518.30.00',
    tipoContenedor: '1x20\' FCL',
    tipoTransporte: 'maritimo',
    fechaPO: '2024-10-25',
    fechaETD: '2024-11-28',
    fechaETA: '2025-01-07',
    fechaArribo: '2025-01-07',
    freeTimeDias: 14,
    freeTimeVence: '2025-01-21',
    canalAduana: null,
    observacionesAduana: null,
    montoTotalUSD: 67400,
    costos: [
      { concepto: 'Mercadería', estimadoUSD: 52000, realUSD: 52000 },
      { concepto: 'Flete', estimadoUSD: 4200, realUSD: 4200 },
      { concepto: 'Seguro', estimadoUSD: 680, realUSD: 680 },
      { concepto: 'Gastos destino', estimadoUSD: 3200, realUSD: null },
      { concepto: 'Impuestos', estimadoUSD: 7320, realUSD: null },
    ],
    pagos: [
      { id: 'PAG-089-1', concepto: 'anticipo_proveedor', descripcion: 'Anticipo 30%', montoUSD: 15600, fechaVencimiento: '2024-10-30', estado: 'pagado' },
      { id: 'PAG-089-2', concepto: 'saldo_proveedor', descripcion: 'Saldo 70%', montoUSD: 36400, fechaVencimiento: '2024-11-25', estado: 'pagado' },
      { id: 'PAG-089-3', concepto: 'flete', descripcion: 'Flete DHL', montoUSD: 4200, fechaVencimiento: '2024-11-28', estado: 'pagado' },
      { id: 'PAG-089-4', concepto: 'despachante', descripcion: 'Honorarios despacho', montoUSD: 1200, fechaVencimiento: '2025-01-10', estado: 'pendiente' },
    ],
    documentos: [
      { tipo: 'invoice', nombre: 'Invoice', estado: 'validado', fechaRecibido: '2024-10-28', obligatorio: true },
      { tipo: 'packing_list', nombre: 'Packing List', estado: 'validado', fechaRecibido: '2024-11-20', obligatorio: true },
      { tipo: 'bl', nombre: 'B/L', estado: 'validado', fechaRecibido: '2024-12-01', obligatorio: true },
      { tipo: 'seguro', nombre: 'Certificado Seguro', estado: 'validado', fechaRecibido: '2024-11-26', obligatorio: true },
      { tipo: 'cert_origen', nombre: 'Certificado Origen', estado: 'validado', fechaRecibido: '2024-11-25', obligatorio: true },
    ],
    hitos: [
      { tipo: 'po', descripcion: 'PO emitida', fecha: '2024-10-25', completado: true },
      { tipo: 'etd', descripcion: 'ETD Shenzhen', fecha: '2024-11-28', completado: true },
      { tipo: 'eta', descripcion: 'ETA Buenos Aires', fecha: '2025-01-07', completado: true },
      { tipo: 'free_time', descripcion: 'Vence free time', fecha: '2025-01-21', completado: false },
      { tipo: 'turno_retiro', descripcion: 'Turno retiro', fecha: '2025-01-10', completado: false },
    ],
    responsable: 'Operaciones',
    alertas: ['Llegó hoy - coordinar turno retiro'],
    bloqueo: null,
    proximaAccion: { texto: 'Coordinar turno retiro', owner: 'Logística' }
  },
  {
    id: 'OP-072',
    nombre: 'Pet Supplies Premium',
    descripcion: 'Camas, transportadoras y juguetes',
    etapa: 'aduana',
    riesgo: 'critico',
    proveedor: 'Yiwu Pet Supplies Ltd.',
    proveedorCiudad: 'Yiwu',
    forwarder: 'Hapag-Lloyd',
    despachante: 'García & Asociados',
    incoterm: 'FOB Ningbo',
    ncm: '4201.00.00',
    tipoContenedor: '1x40\' HQ',
    tipoTransporte: 'maritimo',
    fechaPO: '2024-09-15',
    fechaETD: '2024-10-20',
    fechaETA: '2024-12-15',
    fechaArribo: '2024-12-18',
    freeTimeDias: 14,
    freeTimeVence: '2025-01-09',
    canalAduana: 'rojo',
    observacionesAduana: 'Verificación física - requiere fotos de productos',
    montoTotalUSD: 58000,
    costos: [
      { concepto: 'Mercadería', estimadoUSD: 45000, realUSD: 45000 },
      { concepto: 'Flete', estimadoUSD: 5500, realUSD: 5800 },
      { concepto: 'Seguro', estimadoUSD: 600, realUSD: 600 },
      { concepto: 'Gastos destino', estimadoUSD: 3500, realUSD: 4200 },
      { concepto: 'Impuestos', estimadoUSD: 6400, realUSD: null },
    ],
    pagos: [
      { id: 'PAG-072-1', concepto: 'anticipo_proveedor', descripcion: 'Anticipo 30%', montoUSD: 13500, fechaVencimiento: '2024-09-20', estado: 'pagado' },
      { id: 'PAG-072-2', concepto: 'saldo_proveedor', descripcion: 'Saldo 70%', montoUSD: 31500, fechaVencimiento: '2024-10-18', estado: 'pagado' },
      { id: 'PAG-072-3', concepto: 'flete', descripcion: 'Flete Hapag', montoUSD: 5800, fechaVencimiento: '2024-10-20', estado: 'pagado' },
      { id: 'PAG-072-4', concepto: 'despachante', descripcion: 'Honorarios + gastos', montoUSD: 2800, fechaVencimiento: '2025-01-07', estado: 'vencido' },
      { id: 'PAG-072-5', concepto: 'terminal', descripcion: 'Gastos terminal', montoUSD: 1400, fechaVencimiento: '2025-01-07', estado: 'vencido' },
    ],
    documentos: [
      { tipo: 'invoice', nombre: 'Invoice', estado: 'validado', fechaRecibido: '2024-09-18', obligatorio: true },
      { tipo: 'packing_list', nombre: 'Packing List', estado: 'validado', fechaRecibido: '2024-10-15', obligatorio: true },
      { tipo: 'bl', nombre: 'B/L', estado: 'validado', fechaRecibido: '2024-10-25', obligatorio: true },
      { tipo: 'dui', nombre: 'DUI', estado: 'pendiente', obligatorio: true },
    ],
    hitos: [
      { tipo: 'po', descripcion: 'PO emitida', fecha: '2024-09-15', completado: true },
      { tipo: 'etd', descripcion: 'ETD Ningbo', fecha: '2024-10-20', completado: true },
      { tipo: 'eta', descripcion: 'ETA Buenos Aires', fecha: '2024-12-15', completado: true },
      { tipo: 'free_time', descripcion: 'Vence free time', fecha: '2025-01-09', completado: false },
    ],
    responsable: 'Operaciones',
    alertas: ['CANAL ROJO - responder observación AFIP', 'Free time vence en 2 días', 'Pagos vencidos: $4,200'],
    bloqueo: 'Canal rojo - pendiente respuesta AFIP',
    proximaAccion: { texto: 'Responder observación AFIP', owner: 'Operaciones' }
  },
  {
    id: 'OP-088',
    nombre: 'Juguetes Educativos',
    descripcion: 'Rompecabezas y juegos didácticos',
    etapa: 'aduana',
    riesgo: 'alto',
    proveedor: 'Guangzhou Toys Factory',
    proveedorCiudad: 'Guangzhou',
    forwarder: 'COSCO',
    despachante: 'Bianchi Despachantes',
    incoterm: 'FOB Guangzhou',
    ncm: '9503.00.99',
    tipoContenedor: '1x20\' FCL',
    tipoTransporte: 'maritimo',
    fechaPO: '2024-10-01',
    fechaETD: '2024-11-05',
    fechaETA: '2024-12-28',
    fechaArribo: '2024-12-30',
    freeTimeDias: 14,
    freeTimeVence: '2025-01-15',
    canalAduana: 'naranja',
    observacionesAduana: 'Verificación documental - pendiente validación NCM',
    montoTotalUSD: 35000,
    costos: [
      { concepto: 'Mercadería', estimadoUSD: 28000, realUSD: 28000 },
      { concepto: 'Flete', estimadoUSD: 3800, realUSD: 3800 },
      { concepto: 'Seguro', estimadoUSD: 400, realUSD: 400 },
      { concepto: 'Gastos destino', estimadoUSD: 2800, realUSD: null },
    ],
    pagos: [
      { id: 'PAG-088-1', concepto: 'anticipo_proveedor', descripcion: 'Anticipo 30%', montoUSD: 8400, fechaVencimiento: '2024-10-05', estado: 'pagado' },
      { id: 'PAG-088-2', concepto: 'saldo_proveedor', descripcion: 'Saldo 70%', montoUSD: 19600, fechaVencimiento: '2024-11-01', estado: 'pagado' },
      { id: 'PAG-088-3', concepto: 'despachante', descripcion: 'Honorarios despacho', montoUSD: 1500, fechaVencimiento: '2025-01-08', estado: 'pendiente' },
    ],
    documentos: [
      { tipo: 'invoice', nombre: 'Invoice', estado: 'validado', fechaRecibido: '2024-10-05', obligatorio: true },
      { tipo: 'packing_list', nombre: 'Packing List', estado: 'recibido', fechaRecibido: '2024-11-01', obligatorio: true },
      { tipo: 'bl', nombre: 'B/L', estado: 'validado', fechaRecibido: '2024-11-10', obligatorio: true },
    ],
    hitos: [
      { tipo: 'po', descripcion: 'PO emitida', fecha: '2024-10-01', completado: true },
      { tipo: 'etd', descripcion: 'ETD Guangzhou', fecha: '2024-11-05', completado: true },
      { tipo: 'eta', descripcion: 'ETA Buenos Aires', fecha: '2024-12-28', completado: true },
      { tipo: 'free_time', descripcion: 'Vence free time', fecha: '2025-01-15', completado: false },
    ],
    responsable: 'Operaciones',
    alertas: ['Canal naranja - validar NCM'],
    bloqueo: 'Canal naranja - validación NCM pendiente',
    proximaAccion: { texto: 'Validar NCM con despachante', owner: 'Operaciones' }
  },
  {
    id: 'OP-086',
    nombre: 'Accesorios Tech Varios',
    descripcion: 'Soportes, organizadores y accesorios',
    etapa: 'liberado',
    riesgo: 'bajo',
    proveedor: 'Dongguan Accessories',
    proveedorCiudad: 'Dongguan',
    forwarder: 'MSC',
    despachante: 'García & Asociados',
    incoterm: 'FOB Shenzhen',
    ncm: '3926.90.00',
    tipoContenedor: 'LCL 5 CBM',
    tipoTransporte: 'maritimo',
    fechaPO: '2024-09-20',
    fechaETD: '2024-10-25',
    fechaETA: '2024-12-20',
    fechaArribo: '2024-12-22',
    freeTimeDias: 14,
    freeTimeVence: '2025-01-08',
    canalAduana: 'verde',
    observacionesAduana: null,
    montoTotalUSD: 18000,
    costos: [
      { concepto: 'Mercadería', estimadoUSD: 14000, realUSD: 14000 },
      { concepto: 'Flete', estimadoUSD: 2200, realUSD: 2200 },
      { concepto: 'Seguro', estimadoUSD: 250, realUSD: 250 },
      { concepto: 'Gastos destino', estimadoUSD: 1550, realUSD: 1480 },
    ],
    pagos: [
      { id: 'PAG-086-1', concepto: 'anticipo_proveedor', descripcion: 'Anticipo 30%', montoUSD: 4200, fechaVencimiento: '2024-09-25', estado: 'pagado' },
      { id: 'PAG-086-2', concepto: 'saldo_proveedor', descripcion: 'Saldo 70%', montoUSD: 9800, fechaVencimiento: '2024-10-22', estado: 'pagado' },
      { id: 'PAG-086-3', concepto: 'flete', descripcion: 'Flete MSC', montoUSD: 2200, fechaVencimiento: '2024-10-25', estado: 'pagado' },
      { id: 'PAG-086-4', concepto: 'despachante', descripcion: 'Todo incluido', montoUSD: 1480, fechaVencimiento: '2025-01-05', estado: 'pagado' },
    ],
    documentos: [
      { tipo: 'invoice', nombre: 'Invoice', estado: 'validado', fechaRecibido: '2024-09-23', obligatorio: true },
      { tipo: 'packing_list', nombre: 'Packing List', estado: 'validado', fechaRecibido: '2024-10-20', obligatorio: true },
      { tipo: 'bl', nombre: 'B/L', estado: 'validado', fechaRecibido: '2024-10-28', obligatorio: true },
      { tipo: 'dui', nombre: 'DUI', estado: 'validado', fechaRecibido: '2025-01-06', obligatorio: true },
    ],
    hitos: [
      { tipo: 'po', descripcion: 'PO emitida', fecha: '2024-09-20', completado: true },
      { tipo: 'etd', descripcion: 'ETD Shenzhen', fecha: '2024-10-25', completado: true },
      { tipo: 'eta', descripcion: 'ETA Buenos Aires', fecha: '2024-12-20', completado: true },
      { tipo: 'turno_retiro', descripcion: 'Retiro depósito', fecha: '2025-01-08', completado: false },
    ],
    responsable: 'Logística',
    alertas: ['Coordinar retiro mañana'],
    bloqueo: null,
    proximaAccion: { texto: 'Coordinar retiro mañana', owner: 'Logística' }
  }
];

// ============ DATOS CALCULADOS PARA HOY (FASE 2C) ============

export const URGENT_ITEMS: UrgentItem[] = [
  {
    id: 'URG-001',
    tipo: 'pago',
    texto: 'Pagar gastos destino OP-072',
    operacionId: 'OP-072',
    owner: 'Finanzas',
    dueTime: 'Vencido',
    porQue: 'Pagos vencidos bloquean liberación',
    accion: 'pagos',
    prioridad: 'critica',
    ctaLabel: 'Registrar pago'
  },
  {
    id: 'URG-002',
    tipo: 'aduana',
    texto: 'Responder observación AFIP - OP-072',
    operacionId: 'OP-072',
    owner: 'Operaciones',
    dueTime: 'Hoy',
    porQue: 'Canal rojo requiere respuesta inmediata',
    accion: 'operaciones',
    prioridad: 'critica',
    ctaLabel: 'Responder AFIP'
  },
  {
    id: 'URG-003',
    tipo: 'free_time',
    texto: 'Free time vence en 2 días - OP-072',
    operacionId: 'OP-072',
    owner: 'Logística',
    dueTime: '9 Ene',
    porQue: 'Demurrage $150/día después del vencimiento',
    accion: 'operaciones',
    prioridad: 'critica',
    ctaLabel: 'Coordinar retiro'
  },
  {
    id: 'URG-004',
    tipo: 'embarque',
    texto: 'OP-089 llegó hoy - coordinar turno',
    operacionId: 'OP-089',
    owner: 'Logística',
    dueTime: 'Hoy',
    porQue: 'Free time corre desde hoy',
    accion: 'operaciones',
    prioridad: 'alta',
    ctaLabel: 'Agendar turno'
  },
  {
    id: 'URG-005',
    tipo: 'documento',
    texto: 'B/L pendiente - OP-094 (ETA 12 días)',
    operacionId: 'OP-094',
    owner: 'Logística',
    dueTime: '10 Ene',
    porQue: 'Sin B/L no se puede iniciar despacho',
    accion: 'operaciones',
    prioridad: 'alta',
    ctaLabel: 'Solicitar B/L'
  },
  {
    id: 'URG-006',
    tipo: 'cliente',
    texto: 'TechStore Argentina - 15 días sin pagar ($350K)',
    owner: 'Cobranzas',
    dueTime: 'Esta semana',
    porQue: 'Supera límite de crédito',
    accion: 'cobranzas',
    prioridad: 'media',
    ctaLabel: 'Llamar cliente'
  }
];

export const PROXIMOS_HITOS: ProximoHito[] = [
  { fecha: '2025-01-07', tipo: 'eta', descripcion: 'ETA Buenos Aires', operacionId: 'OP-089', operacionNombre: 'Electrónica Consumo' },
  { fecha: '2025-01-08', tipo: 'turno_retiro', descripcion: 'Retiro depósito', operacionId: 'OP-086', operacionNombre: 'Accesorios Tech' },
  { fecha: '2025-01-09', tipo: 'free_time', descripcion: 'Vence free time', operacionId: 'OP-072', operacionNombre: 'Pet Supplies Premium' },
  { fecha: '2025-01-10', tipo: 'cutoff', descripcion: 'Cut-off documentos', operacionId: 'OP-094', operacionNombre: 'Smart Home Lote 3' },
  { fecha: '2025-01-10', tipo: 'pago', descripcion: 'Pago despachante', operacionId: 'OP-089', operacionNombre: 'Electrónica Consumo' },
  { fecha: '2025-01-15', tipo: 'free_time', descripcion: 'Vence free time', operacionId: 'OP-088', operacionNombre: 'Juguetes Educativos' },
  { fecha: '2025-01-19', tipo: 'eta', descripcion: 'ETA Buenos Aires', operacionId: 'OP-094', operacionNombre: 'Smart Home Lote 3' },
];

export const PAGOS_PROXIMOS: PagoProximo[] = [
  { fecha: '2025-01-07', concepto: 'Gastos destino (VENCIDO)', montoUSD: 4200, operacionId: 'OP-072', beneficiario: 'García & Asociados', categoria: 'despachante' },
  { fecha: '2025-01-08', concepto: 'Honorarios despacho', montoUSD: 1500, operacionId: 'OP-088', beneficiario: 'Bianchi Despachantes', categoria: 'despachante' },
  { fecha: '2025-01-10', concepto: 'Honorarios despacho', montoUSD: 1200, operacionId: 'OP-089', beneficiario: 'García & Asociados', categoria: 'despachante' },
  { fecha: '2025-01-15', concepto: 'Saldo proveedor', montoUSD: 17500, operacionId: 'OP-091', beneficiario: 'Shanghai Components', categoria: 'proveedor' },
  { fecha: '2025-01-20', concepto: 'Saldo proveedor', montoUSD: 26600, operacionId: 'OP-097', beneficiario: 'Guangzhou Toys', categoria: 'proveedor' },
  { fecha: '2025-01-25', concepto: 'Saldo proveedor', montoUSD: 12950, operacionId: 'OP-098', beneficiario: 'Yiwu Pet Supplies', categoria: 'proveedor' },
];

// Fase 2C: Breakdown de caja 7 días
export const CAJA_BREAKDOWN: CajaBreakdown[] = [
  { categoria: 'proveedor', label: 'Proveedores', montoUSD: 57050, color: '#3b82f6' },
  { categoria: 'despachante', label: 'Despachantes', montoUSD: 6900, color: '#8b5cf6' },
  { categoria: 'terminal', label: 'Terminal/Depósito', montoUSD: 0, color: '#f59e0b' },
  { categoria: 'flete', label: 'Fletes', montoUSD: 0, color: '#06b6d4' },
  { categoria: 'impuestos', label: 'Impuestos (est.)', montoUSD: 0, color: '#ef4444' },
];
